# Autogenerated file
def render(network, logger, version):
    yield """

<!DOCTYPE html>
<html lang=\"en\">
    """
# Autogenerated file
    def render1(*a, **d):
        yield """ <head>
    <meta charset=\"utf-8\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <link rel=\"stylesheet\" type=\"text/css\" href=\"/static/styles.css\" />
    <title>Whatnick: Energy Monitor</title>
</head>"""
    yield from render1()
    yield """
	<body>
       """
# Autogenerated file
    def render2(*a, **d):
        yield """<div class=\"masthead\">
    <a href=\"/\" width=\"86.492px\" height=\"76.729px\">
        
    </a>
</div>"""
    yield from render2()
    yield """
        <div class=\"pagesection\">
            <ul class=\"mainmenu\">
                <li>
                    <a href=\"/networks\">
                        Manage network connection
                        <span class=\"details\">Direct access point, no network connected.</span>
                    </a>
                </li>
                <li>
                    <a href=\"/logging\">
                        Data logging service
                        <span class=\"details\">Data stored locally only.</span></a>
                </li>
                <li>
                    <a href=\"/hardware\">
                        Configure hardware
                    </a>   
                </li>
                <li>
                    <a href=\"/firmware\">
                        Update firmware
                        <span class=\"details\">Current version: 0.0.1</span>
                    </a>            
                </li>
            </ul>
        </div>
       """
# Autogenerated file
    def render3(*a, **d):
        yield """<script src=\"/static/vendor/vue_development.js\"></script>"""
    yield from render3()
    yield """
	</body>
</html>"""
