# Autogenerated file
def render(networks):
    yield """

<!DOCTYPE html>
<html lang=\"en\">
    """
# Autogenerated file
    def render1(*a, **d):
        yield """ <head>
    <meta charset=\"utf-8\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <link rel=\"stylesheet\" type=\"text/css\" href=\"/static/styles.css\" />
    <title>Whatnick: Energy Monitor</title>
</head>"""
    yield from render1()
    yield """
	<body>
       """
# Autogenerated file
    def render2(*a, **d):
        yield """<div class=\"masthead\">
    <a href=\"/\">
        
    </a>
</div>"""
    yield from render2()
    yield """
        <div id=\"vue_app\" class=\"pagesection\">
            <div class=\"component\">
               """
# Autogenerated file
    def render3(title):
        yield """

<div class=\"ui__header\">
    <h1 class=\"heading\">"""
        yield str(title)
        yield """</h1>
    <nav class=\"controls\">
    <a href=\"/\" class=\"btn_close\">
    <svg class=\"icon\" width=\"30\" height=\"30\">
       <path d=\"M15.707,15l3.625-3.624c0.194-0.195,0.194-0.512,0-0.707c-0.195-0.195-0.513-0.195-0.707,0L15,14.293l-3.624-3.625
	c-0.195-0.195-0.512-0.195-0.707,0s-0.195,0.512,0,0.707L14.293,15l-3.625,3.625c-0.195,0.194-0.195,0.512,0,0.707
	c0.098,0.096,0.226,0.146,0.354,0.146s0.256-0.05,0.354-0.146L15,15.707l3.625,3.625c0.098,0.098,0.226,0.146,0.354,0.146
	s0.254-0.05,0.352-0.146c0.195-0.195,0.195-0.513,0-0.707L15.707,15z\"/>
    </svg>
    close</a>
    </nav>
</div>"""
    yield from render3('Networks')
    yield """
                <div class=\"ui__body\">
                    <ul class=\"navlist\">
                        """
    for key, network in enumerate(networks):
        yield """
                        <li>
                            <a 
                                v-on:click.prevent=\"accordion($event, """
        yield str(key)
        yield """)\"
                                :class=\"linkClasses("""
        yield str(key)
        yield """)\"
                                href=\"#\"
                            >
                                """
        yield str(network.ssid)
        yield """
                                """
        if network.connected:
            yield """<span class=\"details\"> Connected</span>
                                """
        elif network.pwd:
            yield """<span class=\"details\"> Remembered</span>"""
        yield """
                            </a>
                            """
# Autogenerated file
        def render4(*a, **d):
            yield """<div
    ref=\"acc_"""
            yield str(key)
            yield """\" 
    :style=\"accStyles("""
            yield str(key)
            yield """)\"
    :class=\"accClasses("""
            yield str(key)
            yield """)\"
>
    <form 
        v-cloak 
        class=\"form form__network\"
        method=\"post\"
    >
        <p><label>Password <input name=\"pwd\" id=\"pwd\" type=\"password\" value=\""""
            yield str(network.pwd)
            yield """\"></label></p>
        <p>
        
        <input name=\"ssid\" id=\"ssid\" type=\"hidden\" value=\""""
            yield str(network.ssid)
            yield """\">
        
        """
            if network.pwd or network.connected:
                yield """
            <button name=\"forget\" type=\"submit\" class=\"button button--inv\">Forget</button> 
        """
            yield """
        
        """
            if not network.connected:
                yield """
            <button name=\"connect\" type=\"submit\" class=\"button--inv\">Connect</button>
        """
            yield """
        </p>
    </form>
</div>"""
        yield from render4()
        yield """
                        </li>
                        """
    yield """
                    </ul>
                    
                    <ul class=\"navlist\">
                        <li>
                            <a
                                v-on:click.prevent=\"accordion($event, 'new')\"
                                :class=\"linkClasses('new')\"
                                href=\"#\"
                            >
                                [+] Add network
                            </a>
                            """
# Autogenerated file
    def render5(*a, **d):
        yield """<div 
    ref=\"acc_new\" 
    :style=\"accStyles('new')\"
    :class=\"accClasses('new')\"
>
    <form 
        v-cloak  
        class=\"form form__network\"
        method=\"post\"
        action=\"/networks\"
    >
        <p><label>Name <input name=\"ssid\" type=\"text\"></label></p>
        <p><label>Password <input name=\"pwd\" type=\"text\"></label></p>
        <p><button name=\"connect\" class=\"button--inv\" type=\"submit\">Connect</button></p>
    </form>
</div>"""
    yield from render5()
    yield """
                        </li>
                    </ul>
                </div>
                <div class=\"ui__footer\">
                    <a class=\"button button--inv\" href=\"/networks\">Reload to search again</a>
                </div>
            </div>
        </div>
       """
# Autogenerated file
    def render6(*a, **d):
        yield """<script src=\"/static/vendor/vue_development.js\"></script>"""
    yield from render6()
    yield """
       <script>
            var app = new Vue("""
    yield """{
                el: '#vue_app',
                delimiters: [\"[[\",\"]]\"],
                data:"""
    yield """{
                    networks: [],
                    activeId: '-1'
                },
                methods:"""
    yield """{
                    accordion: function(event, id)"""
    yield """{
                        if(this.activeId === id)"""
    yield """{
                            this.activeId = undefined;
                        }else"""
    yield """{
                            this.activeId = id;
                        }
                    },
                    linkClasses(id)"""
    yield """{
                        if(this.activeId == id)"""
    yield """{
                            return 'active';
                        }
                        return '';
                    },
                    accStyles:function(id)"""
    yield """{
                        // Note: need to ensure accordion is not 'undefined'
                        var accordion = this.$refs['acc_'+id];
                        if(this.activeId != id)"""
    yield """{
                            return """
    yield """{height:'0px'}
                        }else if(accordion && accordion.offsetHeight == 0)"""
    yield """{
                        
                            var style = accordion.firstChild.currentStyle || window.getComputedStyle(accordion.firstChild);
                            var margintop = parseInt(style.marginTop.slice(0,-2));
                            var marginbottom = parseInt(style.marginBottom.slice(0,-2));
                        
                            return """
    yield """{height: accordion.firstChild.offsetHeight+ margintop + marginbottom + 'px'}
                        }else"""
    yield """{
                            return """
    yield """{height:'0px'}
                        }
                    },
                    accClasses:function(id)"""
    yield """{
                        var classes = ['accordion','ani_height'];
                        if(this.activeId == id)"""
    yield """{
                            classes.push('active');
                        }
                        return classes.join(' ');
                    },
                }
            })
        </script>
	</body>
</html>"""
